title: CV | Atakan Naci CAKIR
url: https://aztechgames.github.io/CV
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
